app_user:
  resource: "@AppBundle/Resources/config/routing/user.yml"
  prefix: /

app_publication:
  resource: "@AppBundle/Resources/config/routing/publication.yml"
  prefix: /

app_following:
  resource: "@AppBundle/Resources/config/routing/following.yml"
  prefix: /

app_like:
  resource: "@AppBundle/Resources/config/routing/like.yml"
  prefix: /

app_notification:
  resource: "@AppBundle/Resources/config/routing/notification.yml"
  prefix: /

app_private_message:
  resource: "@AppBundle/Resources/config/routing/private_message.yml"
  prefix: /

#app_mainpage:
  #resource: "@AppBundle/Resources/config/routing/mainpage.yml"
  #prefix: /

app_dating:
  resource: "@AppBundle/Resources/config/routing/dating.yml"
  prefix: /

app_affiliate:
  resource: "@AppBundle/Resources/config/routing/affiliate.yml"
  prefix: /

app_about:
  resource: "@AppBundle/Resources/config/routing/about.yml"
  prefix: /

app_buy_credit:
  resource: "@AppBundle/Resources/config/routing/buy_credit.yml"
  prefix: /

app_traveling:
  resource: "@AppBundle/Resources/config/routing/traveling.yml"
  prefix: /

app_affiliate_signin:
  resource: "@AppBundle/Resources/config/routing/affiliate-signin.yml"
  prefix: /

app_admin:
  resource: "@AppBundle/Resources/config/routing/admin.yml"
  prefix: /

app_homepage:
  path: /
  defaults: { _controller: AppBundle:MainPage:mainPage }
  #defaults: { _controller: AppBundle:User:login }